# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-27 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]


