# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-27 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_auto_20180927_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template_info',
            name='publicpar',
            field=models.CharField(max_length=1000, verbose_name='公共参数'),
        ),
    ]
