# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-17 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0003_auto_20180927_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_info',
            name='jobcontent',
            field=models.CharField(default=1, max_length=1000, verbose_name='Job描述'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_info',
            name='jobtarget',
            field=models.CharField(default=1, max_length=1000, verbose_name='Job目标'),
            preserve_default=False,
        ),
    ]
