# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-26 13:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0004_auto_20181017_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistcs_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runnerstate', models.IntegerField(default=0, verbose_name='运行状态')),
                ('runnertime', models.CharField(max_length=100, verbose_name='执行时间')),
                ('okcount', models.IntegerField(default=0, verbose_name='通过数')),
                ('failcount', models.IntegerField(default=0, verbose_name='失败数')),
                ('errorcount', models.IntegerField(default=0, verbose_name='错误数')),
                ('pnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.Project_info')),
                ('templateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.Template_info')),
            ],
        ),
    ]
